# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-07 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('current_temperature', models.FloatField(blank=True, null=True, verbose_name='current temperature')),
            ],
            options={
                'verbose_name': 'beer',
                'verbose_name_plural': 'beers',
            },
        ),
        migrations.CreateModel(
            name='BeerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='beer type')),
                ('image', stdimage.models.StdImageField(upload_to=stdimage.utils.UploadToClassNameDir())),
                ('serving_temperature', models.FloatField(verbose_name='serving temperature')),
            ],
            options={
                'verbose_name': 'beer type',
                'verbose_name_plural': 'beer types',
            },
        ),
        migrations.AddField(
            model_name='beer',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beers', to='beers.BeerType', verbose_name='type'),
        ),
    ]
