# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-07 13:23
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beertype',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=stdimage.utils.UploadToClassNameDir()),
        ),
    ]
