# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-07 16:01
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0002_auto_20180107_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beertype',
            name='image',
        ),
        migrations.AddField(
            model_name='beer',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=stdimage.utils.UploadToClassNameDir(), verbose_name='image'),
        ),
    ]
