# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-25 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0003_auto_20180107_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='FridgeShelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'fridge shelf',
                'verbose_name_plural': 'fridge shelves',
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='beer',
            options={'ordering': ('id',), 'verbose_name': 'beer', 'verbose_name_plural': 'beers'},
        ),
        migrations.AlterModelOptions(
            name='beertype',
            options={'ordering': ('id',), 'verbose_name': 'beer type', 'verbose_name_plural': 'beer types'},
        ),
        migrations.AddField(
            model_name='fridgeshelf',
            name='beer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='beers.Beer', verbose_name='beer'),
        ),
    ]
