# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-25 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0004_auto_20180125_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='current_temperature',
        ),
        migrations.AddField(
            model_name='fridgeshelf',
            name='current_temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='current temperature'),
        ),
    ]
